apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentOfNexus
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          resources:
            limits:
              memory: "4Gi"
              cpu: "1000m"
            requests:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
      volumes:
        - name: nexus-data
          emptyDir: {}  
---
apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: test
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8081'
spec:
  selector: 
    app: nexus
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 808