apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: test
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        runAsUser: 0
      volumes:
      - name: docker-v 
        hostPath: 
          path: /var/run/docker.sock
      containers:
      - name: jenkins
        image: jenkins/jenkins:alpine
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: docker-v 
          mountPath: /var/run/docker.sock

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: test
  labels:
    app: jenkins
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: jenkins
