apiVersion: apps/v1
kind: Deployment
metadata:
 name: sonarqube-deployment
 namespace: test
 labels:
    app: sonarqube
spec:
  selector:
    matchLabels:
     app: sonarqube
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:latest
        ports:
          - containerPort: 9000
            protocol: TCP
    
---
apiVersion: v1
kind: Service
metadata:
    name: sonarqube
    namespace: test
    labels:
        app: sonarqube
spec:
    selector: 
       app: sonarqube
    type: LoadBalancer   
    ports:
      - port: 80
        protocol: TCP
        targetPort: 9000
    