---
# tasks file for jenkins
- name: jenkins_deployment
  k8s:
    state: present
    kubeconfig: "{{ kube_config }}"
    src: /home/salah/ITI/Ansible/DevOps-challenge/roles/jenkins/files/jenkins.yaml