pipeline {
   agent any
   stages {
       stage('Build') {
           agent {
               docker {
                   image 'golang'
               }
           }
           steps {
               // Create our project directory.
               sh 'cd ${GOPATH}/src'
               sh 'mkdir -p ${GOPATH}/src/hello-world'
               // Copy all files in our Jenkins workspace to our project directory.
               sh 'ls ${WORKSPACE}'     
               sh 'cp -r ${WORKSPACE}/CICD_Pipeline/*.go ${GOPATH}/src/hello-world'
               sh 'ls ${GOPATH}/src/hello-world'         
               // Build the app.
               sh 'go build'              
           }    
       }
       stage('Test') {
           agent {
               docker {
                   image 'golang'
               }
           }
           steps {                
               // Create our project directory.
               sh 'cd ${GOPATH}/src'
               sh 'mkdir -p ${GOPATH}/src/hello-world'
               // Copy all files in our Jenkins workspace to our project directory.               
	       sh 'cp -r ${WORKSPACE}/CICD_Pipeline/*.go ${GOPATH}/src/hello-world'
               // Remove cached test results.
               sh 'go clean -cache'
               // Run Unit Tests.
               sh 'go test ./main_test.go'           
           }
       }
       stage('Publish') {
           steps{
               script {
                   def appimage = docker.build "myapp" + ":$BUILD_NUMBER"

               }
           }
       }



 
       stage ('Deploy') {
           steps {
               script{
                   def image_id = "myapp" + ":$BUILD_NUMBER"
                   sh 'ansible-playbook CICD_Pipeline/playbook.yaml --extra-vars \"image_id=${image_id}\"'
               }
           }
       }
   }
}
